create table souls (
  id int unsigned primary key auto_increment not null,
  name varchar(255) not null,
  image VARCHAR(255),
  hp VARCHAR(255),
  souls VARCHAR(255),
  description text not null
);

INSERT INTO souls (name,image,hp,souls,description) VALUES ('Asylum Demon',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0036_Asylum%20Demon.jpg",825,2000,'If you stand in the doorway and look up, you will see the Asylum Demon waiting above the area at the far end. As you enter the room, he leaps down. You may either fight him then or escape via a gate that closes on crossing it, on the left side of the area. If you choose to evade, you will still have to face him a little later, but with the benefit of having more equipment.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Bell Gargoyle',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0035_Bell%20Gargoyle.jpg",1000,10000,'Located on the roof of the Undead Parish, guarding the path to one of the Bells of Awakening. Not just one, but two of these halberd-wielding, fire breathing demons must be killed for the player to proceed.');
INSERT INTO souls (name,image,hp,Souls,description) VALUES ('Capra Demon',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0034_Capra%20Demon.jpg",1176,6000,'The Capra Demon is the boss of the Lower Undead Burg. You can get to him either by going left, down to the end of the main street (past the Undead Assassins and Undead Dogs), or by going through the shortcut in the waterway in the Firelink Shrine after you unlock it.This boss is highly susceptible to fire, therefore, any variation of the Firebomb or a Charcoal Pine Resin-coated weapon, will go a long way.This particular boss is later found in packs, in the Demon Ruins, where they can be farmed for a decent amount of souls, and potentially, their weapon. See more below.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Ceaseless discharge',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0033_Ceaseless%20Discharge.jpg",4000,20000,'Not only an imposing fire-based boss found in the Demon Ruins, Ceaseless Discharge, as his name may suggest, is the source of the lava flow. Killing him will cease the discharge of lava in the lower parts of the ruins, allowing access to the deeper areas of the map, and progress in the campaign.He was also confirmed to  in fact, be the younger brother of the Daughters of Chaos.He is a passive enemy unless you attack him or loot the Gold-Hemmed Black Set, in which case, he becomes hostile.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Centipede Demon',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0032_Centipede%20Demon.jpg",3432,40000,'This demon is a large bug like creature which defends the path to Lost Izalith. Its arms and tail are separate living centipedes. The boss has a tendency to stand on the lava after walking through the fog gate and repeatedly use his reaching attack. For someone who is not in possession of the Orange Charred Ring or ranged attacks, this can be extremely annoying.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Chaos Witch Quelaag',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0031_Chaos%20Witch%20Quelaag.jpg",3139,20000,'A half-woman, half-spider demon located in a lair near the bottom of Blighttown. One of the Witch of Izaliths daughters, transformed into a monster by the Flames of Chaos. Her notable siblings are The Fair Lady and Ceaseless Discharge. She guards the second Bell of Awakening, and the entrance to her sisters domain.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Crossbreed Priscilla',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0030_Crossbreed%20Priscilla.jpg",2300,30000,'Half dragon boss found in Painted World of Ariamis. An optional boss, she wields a giant scythe and has the ability to turn invisible. If you do not wish to fight her, simply walk past her after talking to her, and proceed towards the open ledge to trigger a cutscene and your return to Anor Londo. (speaking with her doesnt make her aggressive)');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Dark Sun Gwyndolin',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0029_Dark%20Sun%20Gwyndolin.jpg",2000,40000,'The last born of Lord Gwyn, Gwyndolin is the leader of the Blade of the Dark Moon covenant and the only remaining deity in Anor Londo. Gwyndolins followers are few, but their tasks are of vital importance. Although born male, due to magic and association with the moon, Gwyndolin was raised as a daughter. Gwyndolin is biologically a male and is referred to as male by Gwynevere, who lovingly calls him brother. Gwyndolin created the illusion of a sister Gwynevere to help guard over Anor Londo. An unmasking of these deities would be tantamount to blasphemy');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Demon Firesage',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0028_Demon%20Firesage.jpg",5950,20000,' A large demon found at the end of the Demon Ruins. It very closely resembles the Stray Demon and Asylum Demon, though its behavior and abilities are much more closely related to the former of the two bosses.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Four Kings',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0027_Four%20Kings.jpg",9604,60000,'The wraith-like remnants of the four leaders of New Londo Ruins who fell to dark after being tempted with the art of lifedrain. Defeating the Four Kings is necessary to the plot, and is also needed for those players wishing to join the Darkwraith covenant as they must defeat the Four Kings before obtaining the Lordvessel from Anor Londo and talking to Kingseeker Frampt.You can also obtain the Lordvessel then go to kill the Four Kings instead of talking to Frampt.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Gaping Dragon',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0026_Gaping%20Dragon.jpg",4401,25000,'The Gaping Dragon is the boss in the Depths, and gives you the key to the upper entrance to Blighttown.This boss is optional with the Master Key as one chosen gift during character creation, which can be used to enter Blighttown through the back entrance in Valley of Drakes. This is most easily accomplished by simply taking the elevator down from underneath Firelink Shrine, and then circling around into the adjacent building, unlocking the barred door with the Master Key, and then proceeding across the narrow footbridge into the dark cave on the other side.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Great Grey Wolf Sif',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0025_Great%20Greywolf%20Sif.jpg",3432,40000,'A very large wolf who resides in a serene graveyard, across the river from Darkroot Garden. It can also be reached by climbing up the ladder close to the Hydra in Darkroot Basin.According to lore, Sif was Artorias the Abysswalkers partner. When Artorias was swallowed by the Abyss, he threw up his Greatshield to protect Sif, as he could no longer bear it with his arm broken. Now, Sif guards their fallen comrades grave and his ring, to ensure that what happened to Artorias, doesnt happen to anyone else.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Gwyn Lord of Cinder',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0024_Gwyn%20Lord%20of%20Cinder.jpg",4250,70000,'Gwyn, Lord of Cinder was a mighty warrior and the greatest of lords. He was known as the Lord of Sunlight and headed the efforts to end the Age of Ancients, together with Gravelord Nito, the Witch of Izalith, and the dragon-traitor, Seath the Scaleless. Commanding his knights, he led the Lords to victory and oversaw the Age of Fire. Despite being partially bequeathed to the Four Kings and Seath the Scaleless, his soul remains "a powerful thing indeed".');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Iron Golem',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0023_Iron%20Golem.jpg",2880,40000,'The last trial of Sen Fortress, the Iron Golem. The boss is located on a bridge at the top of the fortress, and must be defeated in order to reach Anor Londo.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Moonlight Butterfly',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0022_Moonlight%20Butterfly.jpg",1255,10000,'This is the boss of the first area of the Darkroot Garden. It can be found at the top of a moss covered staircase past the sleeping Stone Giants. The battle takes place on a long stone bridge with the Moonlight Butterfly flying next to it.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Nito',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0021_Nito.jpg",4317,60000,'Holder of one of the four Lord Souls, Gravelord Nito was among the lords to wage war against the dragons. As the Lord of Death, Nito rules over the dead in The Catacombs and resides within the Tomb of Giants. His army of skeletons guard his tomb, while his Gravelord Servants spread death through the Eyes of Death.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Ornstein and Smough',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0020_Ornstein%20&%20Smough.jpg",4000,50000,'Ornstein is the captain of the Four Knights of Gwyn Lord of Cinder, serving alongside Artorias the Abysswalker, Lord Blade Ciaran, and Hawkeye Gough. As his name would suggest, he was an honorary dragon slayer.He wields his Dragonslayer Spear, a sword-spear after the fashion of Gwyn Firstborn own weapon. He also commands the power of lightning. It is believed that he was left behind with Smough to guard Anor Londo cathedral after the gods fled.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Pinwheel',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0019_Pinwheel.jpg",1326,15000,'Pinwheel is the boss that lies in the depths of The Catacombs, and arguably the easiest boss in the entire game. You can find his chamber beyond a fog wall, across the valley floor containing blacksmith Vamos at the bottom of the Catacombs that is being patrolled by the Wheel Skeletons.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Seath the Scaleless',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0018_Seath%20the%20Scaleless.jpg",5525,60000,'Envy and bitterness: words used to describe Seath betrayal of his own kind; unlike his brethren, Seath was born without the stone scales of the Everlasting Dragons. Seath, with the help of Gravelord Nito, the Witch of Izalith, and Gwyn, the Lord of Cinder, brought his own race to the brink of extinction, with many believing him to be the last of his kind.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Stray Demon',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0017_Stray%20Demon.jpg",5250,20000,'A large demon found after returning to the Northern Undead Asylum. This is actually the first demon you see in the game; as you exit your cell at the beginning he can be seen stomping around to your right through the bars in the hallway.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Taurus Demon',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0015_Taurus%20Demon.jpg",1215,3000,'A minotaur-esque demon found on top of a narrow castle wall in the Undead Burg, on the road to the Undead Parish. Similar to the Bell Gargoyles encountered later, the Taurus Demon does not immediately appear when the host passes through the fog gate. Rather, the host must travel approximately halfway across the section before the boss appears atop the far tower and leaps down.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('The bed of Chaos',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0016_Bed%20of%20Chaos.jpg",02,60000,'In a futile attempt to prolong the Age of Fire, the Witch of Izalith tried to recreate the First Flame. The ritual was a failure and its power formed a bed of life which would become the source of all demons; trapping two of her daughters in the orbs on either side, and herself within it.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Artorias the Abysswalker',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0038_Artorias.jpg",3750,50000,'Knight Artorias was one of the four Knights of Gwyn, the commanding knights of Lord Gwyn army. Artorias had an unbendable will of steel, which both helped and fed his hatred for servants of the Dark, particularly the Darkwraiths of Kaathe.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Black Dragon Kalameet',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0039_Black%20Dragon%20Kalameet.jpg",5000,60000,'Kalameet appears for the first time while the player is traveling through the Royal Wood; he lands in a bridge and watches the player for a couple of seconds before flying away, similar to what the Red Wyvern does in Undead Burg. Kalameet can actually be targeted and hit while briefly perched on the bridge (such as by ranged weapons) but cannot be injured.');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Manus Father of The Abyss',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0040_Manus.jpg",6665,60000,'Manus, Father of the Abyss is a final boss of the AotA expansion. While something of a demon in appearance when encountered by the player, Manus was in fact once human. He became the Father of the Abyss when his humanity went wild, but it is not known what caused this');
INSERT INTO souls (name,image,hp,souls,description) VALUES ('Sanctuary Guardian',"https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0041_Sanctuary%20Guardian.jpg",2560,30000,'The white winged lion sanctuary watchkeeper, who dreaded the spread of the Abyss.The Guardian exhibited traits of several animals other than lions, suggesting that it was no ordinary beast, but rather closer to the beings known as Demons.The Sanctuary Guardian is a huge manticore guarding the entry to Oolacile Sanctuary. Its a powerful creature that functions as the first boss of the DLC area, and a hint for whats to come.');






create table enemygame (
  id int primary key auto_increment not null,
  DLC VARCHAR(255) not null,
  Requis VARCHAR(255) not null
);